### ISSUE TITLE
Hold blameless postmortem tabletop exercise

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-project-management#28]
We should hold a tabletop exercise to begin fleshing out our blameless postmortem process for incident response. Using [this hard-coded API key](https://github.com/fecgov/fecfile-online/issues/31) as a low-stakes example, we should walk through incident response for credential leaks. This example is low-stakes because the key has no elevated rate limits.

**Acceptance criteria**
- [x] All-team blameless postmortem meeting held using the [blameless postmortem template](https://drive.google.com/drive/folders/1zQ4OgMSy6hwoTIwVJXtYRzAiZRcSuLM7?ths=true)

**Comment by WiseQA** [comment]
No QA action on this ticket, meeting has been completed.  Moving ticket to Stage Ready in Sprint 2.
