### ISSUE TITLE
Suspend Phase I AWS account

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-project-management#31]
Once we're confident we have all the moving parts needed to run FECfile in cloud.gov, we should spin down/suspend the AWS account so we're not paying for it anymore. We should preserve the account so we can reference the infrastructure if we need to.

### QA Notes ###

 
 null

### DEV Notes ###

 
 null

### Design ###

 
 null

[FECFILE-54](https://fecgov.atlassian.net/browse/FECFILE-54)

**Comment by AureliaKhorsand** [comment]
This is a test comment, please ignore.
