### ISSUE TITLE
WIREFRAME: Allow user to add another user to committee account

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-project-management#32]
Given the user is a Committee Administrator
When they access the Add User Page (Profile > Add User)
Then they will be able to add users as Backup Committee Administrators (term TBD) by entering:

Last Name
First Name
Email Address
Question: Is name and Contact Number actually needed? If so, why?
And when they click Add User, the system will notify the added user by email.

**Comment by MitchellTCG** [comment]
@mary-tcg @JonellaCulmer 
Three Choices to choose from. We can review in the morning.

Huge Tooltip
https://images.zenhubusercontent.com/417265237/a8afce2c-d4c1-4f33-a6bb-21188a55a5f9/add_new_user_2_committee_v1.mp4

Stack Radio Buttons
https://images.zenhubusercontent.com/417265237/04a4fb34-5477-4093-81a1-7e2a91c19e85/add_new_user_2_committee_v2.mp4

Dropdown w/Accordion
https://images.zenhubusercontent.com/417265237/38957474-34ea-43d9-966b-9894bc952349/add_new_user_2_committee_v3.mp4

**Comment by MitchellTCG** [comment]
Here is the Approved version with Radio Buttons and a Tooltip:

![Add_New_User_2_Committee_Tootip.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/faba6e56-ff7c-4f00-8647-03524600a141)

![Add_New_User_2_Committee_Filled_Out.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/c7385879-67d3-4306-9657-9a69bd3ed433)

https://images.zenhubusercontent.com/417265237/84d7eaf6-271a-47d5-9125-fd8e902a9047/add_new_user_2_committee_v2.mp4

**Comment by AureliaKhorsand** [comment]
Test comment, please ignore.
