### ISSUE TITLE
WIREFRAME: Allow user to create Candidate contact using Lookup feature (App #108)

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-project-management#34]
The wire will be based on the following requirements:

Business Reason
As a Committee Administrator, I will be able to create a Candidate contact associated with my committee using the Lookup feature to find a Candidate already registered with FEC so that I can pull them into necessary transactions and reports as needed.

Acceptance Criteria
If I am a Committee Administrator When I access my committee's contact list And add a new contact with the Type "Candidate" Then I will be able to use the Lookup feature to find and select a Candidate registered with FEC by name or ID And the Lookup results will provide me with the candidate name, ID, and office sought And when I select the right candidate, the system will pull in the following to the contact form:
	•	CANDIDATE ID (A/N-9, required)
	•	LAST NAME (A/N-30, required)
	•	FIRST NAME (A/N-20, required)
	•	MIDDLE NAME (A/N-20, not required)
	•	PREFIX (A/N-10, not required)
	•	SUFFIX (A/N-10, not required)
	•	STREET 1 (A/N-34, required)
	•	STREET 2 (A/N-34, not required)
	•	CITY (A/N-30, required)
	•	STATE (A/N-2, required. Should be a dropdown)
	•	ZIP (A/N-9, required)
	•	COUNTRY (dropdown, required. Should default to United States. This may need to be entered automatically by the system)
	•	TELEPHONE (N-10, not required.)
	•	EMPLOYER (A/N-38, not required for a new contact)
	•	OCCUPATION (A/N-38, not required for a new contact)
	•	CANDIDATE OFFICE (Dropdown: House, Senate, Presidential. Required)
	•	CANDIDATE STATE (A/N-2, should be a dropdown, and required if Office = House or Senate)
	•	CANDIDATE DISTRICT (A/N-2, required if Office = House)
Dev Notes: Reuse functionality from fec.gov for lookup, but will also need to build in pulling full data for contact.
See data fields needed here
Dropdown example from fec.gov that we are basing design off of: ￼

**Comment by MitchellTCG** [comment]
@mary-tcg @JonellaCulmer 
Attached you will find two wireframes and an accompanying Prototype Video

![Add_New_Contact_Candidate_Lookup.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/f976d2c7-3c38-40c2-ae79-2671f70f394b)

![Add_New_Contact_Candidate_Manual.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/4e4256a8-d4c7-40cd-9b27-f6797ce16fcb)

https://images.zenhubusercontent.com/417265237/c2e27c43-4252-400a-920f-e445ced9caf7/add_new_contact_candidate.mp4

**Comment by MitchellTCG** [comment]
Updated text!

[Committee – 3.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/f58b3751-3aca-4c72-a016-75acdfd85f46)

**Comment by JonellaCulmer** [comment]
@MitchellTCG Looks great. I think this format for reviewing works great. That way I can take more time to look at mockups and I'll be able to notice stuff easier. For example, we should spell out information for the second radio button. :[]
