### ISSUE TITLE
WIREFRAME: Allow user to view contacts (App #75)

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-project-management#36]
The initial wireframes will be a redesign of Contact Page table. This Wireframe will be further updated after the below questions are answered and requirements are fully flushed out:

Allow user to view contacts#75
Needs user research and redesign.

### Business Reason ###
As a Committee Administrator, I will be able to view all contacts in my committee so that I can group transactions by entity for fundraising purposes or to disclose transactions in aggregate per contact.

### Acceptance Criteria  ###
If I am a Committee Administrator
When I go to Contact Management
Then I will be able to see all contacts associated with my committee.

Currently defaults to Name, Entity Type, Employer, and Occupation.

Questions:

What column defaults are most useful to you now, in OP1?
There are currently no stories for filtering or searching this table. Should these be added to the backlog as future enhancements?
What other functionality would you like to see on this page now in OP1?

**Comment by MitchellTCG** [comment]
@mary-tcg @JonellaCulmer 
Here is an initial wireframe. Final signed off on requirements is needed.

![Manage_Contacts.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/da07c05c-2b63-4702-8dd2-d036bd8ef58e)

**Comment by JonellaCulmer** [comment]
@MitchellTCG My only comment was to: 
- Change "New" button language to "Add new contact"

We also discussed: 
- Rearranging icon and text for "Import" and "Export" buttons
- Modifying icons for "Import" and "Export" buttons

**Comment by MitchellTCG** [comment]
Updated Version:
Added " Add new contact" ion sentence case
fixed Import and Export buttons

![Manage_Contacts_v2.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/889a3c9d-7c5c-47c2-9b18-df440e00288d)

**Comment by MitchellTCG** [comment]
updated!

[Manage_Contacts_v4.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/9e75b3d8-b46c-47a0-8dff-859fdecff745)
