### ISSUE TITLE
WIREFRAME: Allow User to View and Manage Users (#201)

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-project-management#37]
To replace the "+Add User" page currently available under the Profile dropdown.

The "+Add User" dropdown needs to be change to "Manage User" (this is tentative)

The current page will just have a Manage User Table with a button to add a new user. The New User Modal will be will pop up when you click the "New" button.
(ADD NEW USER wireframe can be found [here](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/fecgov/fecfile-project-management/32))

**Comment by MitchellTCG** [comment]
Here is an initial wireframe. Final signed off requirements are needed.

![Manage_Users.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/251cb9f8-9dcc-4509-8c76-81d5b2f2f05c)

**Comment by JonellaCulmer** [comment]
@MitchellTCG Comments I have:
 - Modify "New" button color to match Manage contacts page
 - Change "New" button language to "Add new user"

**Comment by MitchellTCG** [comment]
@JonellaCulmer  @mary-tcg 

Updated:
Changed button to blue and to read "+ Add new user"

![Manage_Users_v2.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/4e78d301-6b10-4cd8-bab0-d563a10f7be3)

**Comment by MitchellTCG** [comment]
Hopefully final update.
@AureliaKhorsand @JonellaCulmer @mary-tcg 

Per our convo with Laura on Monday, we will need a status column. here is the wire.

![Manage_Users_v3.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/fb48aef5-f1c4-4c69-addc-db103a2c7cf3)

**Comment by MitchellTCG** [comment]
@JonellaCulmer  @lbeaufort @AureliaKhorsand 

### Re: why we added the Status column back into the wire... ###
The why we did this is a long answer but Laura stated that the Login.gov workflow will require a pending state when the invite for access is sent. after the user logs in the first time via Login.gov it will automatically change to registered.

Laura can explain it better than I.
