### ISSUE TITLE
WIREERAME: Allow user to view reports (#165)

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-project-management#44]
### Business Reason ### 

As a Committee Administrator, I will be able to view a list of reports associated with my committee account so that I can manage reports as needed.

### Technical Notes ### 

- The status and date/time fields will be placeholders until the data is added to the system
- Create a Django fixture that creates a set of test reports for testing

### Acceptance Criteria ### 

**Given** I am a Committee Administrator 
**When** I go to the reports management page for my committee account
 **Then** I will see a list of reports associated with my committee account and the following information for each:

- Type of Report (e.g., Form 3X) - Is this the type of report meant here? What about quarterly, monthly, special, etc?
- Coverage Dates
- Status - this is a placeholder for now
- Original/Amended
- Date/Time Filed

**Comment by MitchellTCG** [comment]
@JonellaCulmer @mary-tcg @AureliaKhorsand @alexander-lin 

Here is the wire for the Reports page table

![Manage Reports.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/60cd8151-3c0d-4613-b9c4-07c7e223fc2a)

**Comment by MitchellTCG** [comment]
@JonellaCulmer @mary-tcg @AureliaKhorsand 

Here is an Updated Mock

Changes made:
Changed "Create a new reports" to "Create a new report"
Made "New/Amended" column header to "Version"
Changed options in Version column from "New or Amended" to "Original or Amendment"
Changed Column header to sentence case

![Manage Reports.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/43d702af-2e5b-44a1-8ae6-bdb728046bf0)

![Manage Reports with more option.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/c81cc4f3-4242-43c3-b510-a5220cd87735)

https://images.zenhubusercontent.com/417265237/9750cb40-1b74-4395-a1cc-e2b5ed1d54a8/manage_reports_with_more.mp4

**Comment by MitchellTCG** [comment]
@JonellaCulmer @AureliaKhorsand @mary-tcg 

Thoughts on whether 'Form type' or 'Report type' should be the first column

Options:
![Manage Reports – Form type.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/a491faae-95f3-451d-a088-ecabb7f30043)

![Manage Reports – Report type.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/84c154dd-88db-48ba-a4d1-76f1694b344c)

**Comment by JonellaCulmer** [comment]
@MitchellTCG Form type first then Report type appears to establish a bit of hierarchy to the list.
