### ISSUE TITLE
88 - Wireframe: Allow user to recover a deleted contact

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-project-management#50]
Related to this ticket:
https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/gh/fecgov/fecfile-web-app/88

Please create 3-4 mocks of how you would recover a deleted contact from the system

Ideally the user would do this from the Manage Contacts Page

It could be a Recycling Bin or something else.

Due COB Friday, Jan 6, 2023

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg is this now OBE, and can it be closed?
