### ISSUE TITLE
756 - Wireframe:System to truncate the field if Purpose Description is greater than 100 characters

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-project-management#54]
Here are the requirements:

1.  Business Reason

       #

       As a FECfile Online user, I should see that transactions with system generated Purpose Descriptions that contain a long entity name are truncated so that they do not exceed 100 characters.

1.  Acceptance Criteria

       #

       Given a system-generated Purpose Description

       If the description is longer than 100 characters

       Then they system will truncate the description to 100 characters. (Ask devs: when?)

UX/UI Question: Should the user receive a warning or message that their CPD is being truncated?

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
#
Simply make a wireframe that has this text in a Purpose description field.

Use a filled out version of any transaction. that has system-generated text. and place this text in there. it is 100 characters long already: 

"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium..."
![Custom Size – 34.png](https://images.zenhubusercontent.com/621cecaf32b9700fedb7b3e6/5732d8ff-78eb-48be-97e1-3ef2361391f8)

 See full ticket and images here: [FECFILE-66](https://fecgov.atlassian.net/browse/FECFILE-66)

**Comment by mary-tcg** [comment]
@MitchellTCG updated wireframe
