### ISSUE TITLE
828 - Wireframe: System to default order transactions *within* a report

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-project-management#55]
Look at dependency line to see requirements

use jonella base to start a wireframe that is ordered like aurelia has asked

download jonella's sketch file from here:
https://drive.google.com/drive/folders/1azmgThp32QJ5rpaVw88YTc6TR_ugCJQu

Manage all transactions.sketch

and open in XD.

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg please note that we want to incorporate the line number of the transaction if possible in this iteration.
