### ISSUE TITLE
283 - Detail Summary Page Updates

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-project-management#59]
the goal here is to update the DETAIL SUMMARY
Mitchell added incorrect text to an old wireframe that led to these correction.

Also Mitchell has updated some lines here:
[https://app.zenhub.com/files/417265237/79627d05-14f4-4963-a0bd-0fd1e8deefb6/download](https://app.zenhub.com/files/417265237/79627d05-14f4-4963-a0bd-0fd1e8deefb6/download)

**Comment by MitchellTCG** [comment]
This is an updated DSP

![Detailed Summary Page – 3.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/88f1fbba-3e6f-48e4-ad25-a688be2dfc1d)

**Comment by MitchellTCG** [comment]
These are the calculations
![Detailed Summary Page – Pop ups.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/cf743e3f-5b85-4bf4-a342-b046645c51fe)

**Comment by MitchellTCG** [comment]
@JonellaCulmer 

Please review

**Comment by MitchellTCG** [comment]
@alexander-lin  @AureliaKhorsand 
Jonella and Mary already have access to this wire

**Comment by MitchellTCG** [comment]
Here is the Proto-video
https://images.zenhubusercontent.com/417265237/d98e0c61-3df5-42b1-b5e3-5423ac14c1bc/283_dsp_system_to_calculate_contributions_line_11_and_33_column_a.mp4

**Comment by MitchellTCG** [comment]
Here are files with tooltips:

Line 11d
![Detailed Summary Page – Line 11d.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/5ae5b2c0-77a0-4a2d-a27a-e824b658262a)

Line 15
![Detailed Summary Page – Line 15.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/7987efe4-d2f7-42d5-8f7b-ba1787a1fb3d)

Line 18c
![Detailed Summary Page – Line 18c.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/0fa2667d-4c92-445f-ad2f-414881a3cb23)

Line 19
![Detailed Summary Page – Line 19.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/09c2da42-0d49-4b44-a62b-e37324f9b86b)

Line 20
![Detailed Summary Page – Line 20.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/fe88f370-740d-4d02-a3f4-aabfe87c7082)

Line 21c
![Detailed Summary Page – Line 21c.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/6239f2e8-cc0d-409a-aaaa-c4fa4e5f866b)

Line 28d
![Detailed Summary Page – Line 28d.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/53971c61-9609-44fa-bbcb-76d5a0a419f0)

Line 30c
![Detailed Summary Page – Line 30c.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/ddbebe25-3413-4fb9-bc02-9c12ad912ef6)

Line 31
![Detailed Summary Page – Line 31.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/382cf715-055f-46ac-9e06-ce4490071e41)

Line 32
![Detailed Summary Page – Line 32.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/2f79880c-e313-4816-8779-9f01a31f1802)

Line 33
![Detailed Summary Page – Line 33.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/1b0b3546-708f-4ec2-97e8-1b2931c9a9b4)

Line 34
![Detailed Summary Page – Line 34.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/8c114615-32f3-4d15-9e39-d5e73845709f)

Line 35
![Detailed Summary Page – Line 35.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/0a9cac74-6b94-4344-b136-99c691e1ab3f)

Line 36
![Detailed Summary Page – Line 36.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/e48b484f-05a1-4181-b158-37715c3b7994)

Line 37
![Detailed Summary Page – Line 37.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/26fbc32e-0dba-410a-ac83-1beda1137998)

Line 38
![Detailed Summary Page – Line 38.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/fc843ec4-ad48-4291-9d53-4dad0b3dfdab)

**Comment by AureliaKhorsand** [comment]
@GreggMoreland
