### ISSUE TITLE
642 & 739 - Wireframes: Allow user to enter In-Kind Receipt on Schedule A (Group A)

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-project-management#62]
Please create a wire for when you create a schedule A the system will create a schedule B

Schedule A
https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/gh/fecgov/fecfile-web-app/642

Schedule B
https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/gh/fecgov/fecfile-web-app/739

Here is a updated version of the in-kind receipt and in-kind out:

1. 
![642 - In-kind Receipt Accordion.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/b2e8a709-5c96-485b-8198-261e5699d8d0)

2. 
![642 - In-kind Receipt.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/79a89ec5-d366-494c-8f60-37b2251f4d5b)

3. 
![739 - In-kind out.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/f5bd1ba8-8004-41ad-931c-8d02d85d4240)

**Comment by MitchellTCG** [comment]
@mary-tcg @JonellaCulmer @AureliaKhorsand 

please review and provide notes/thoughts

**Comment by AureliaKhorsand** [comment]
@MitchellTCG I'm wondering if we need to explicitly show them the transaction data of the In-Kind Out. It's all the same information, and are we asking a lot for the user to view it right then and there if maybe they don't even care? Just a thought. Perhaps just a confirmation message saying that it will create the In-Kind out and they can view it in Disbursements (but keep the explanatory text at the top, I like that)

**Comment by AureliaKhorsand** [comment]
@MitchellTCG can we mark this as complete? Final wires look great
