### ISSUE TITLE
Wireframe for 171 - Allow user to reattribute a transaction within current report

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-project-management#64]
Here is a first crack at reattribution:

Transaction table:
![171 - Allow user to reattribute a transaction within current report.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/7ef571a0-685e-460c-9c13-83aeb79db9d2)

Step One:
![171 - Reattribution 1.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/80a4126b-c20c-4afc-84be-a5a0401fc724)

Step Two:
![171 - Reattribution 2.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/31f564d7-5653-4c95-a4f6-b886c42777bf)

**Comment by MitchellTCG** [comment]
@mary-tcg  @JonellaCulmer 

Here is what i was thinking about for Reattribution

**Comment by AureliaKhorsand** [comment]
Closing as complete as this feature is being developed.
