### ISSUE TITLE
Wireframes: 624 - Allow user to reattribute a transaction from a previous report

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-project-management#65]
Here is a first crack

1.
![624 - Allow user to reattribute a transaction from a previous report.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/f0b2aac7-2e3c-44c7-915e-a4f532621b73)

2.
![624 - Reattribution Previous 1.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/fc73ff4f-a6dc-4616-b5b6-739322433960)

3. 
![624 - Reattribution Previous 2.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/4c8c413c-7834-4767-85dd-01b55110d129)

**Comment by MitchellTCG** [comment]
@mary-tcg @JonellaCulmer @AureliaKhorsand 

please review

**Comment by AureliaKhorsand** [comment]
@MitchellTCG can we talk through this? I'm a little confused. It's a lot of information for essentially just asking - how much money do you want to reattribute to another person, and who is that person? I wonder if we can simplify the workflow at all?

**Comment by MitchellTCG** [comment]
Design has changed
Closing this
