### ISSUE TITLE
Please review these wires for 1003, 1011, 1012, & 1005

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-project-management#66]
Once you have signed off on the wires here, I can add them to actual tickets

**Comment by MitchellTCG** [comment]
**Please review 1003 below:**
![1003 - Loan Received from Bank.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/04215b9e-afa3-462f-beec-c844b605a27b)

**Only caveats:**
Since we have agreed to use radio buttons if yes/no is optional, I have chosen to use a toggle for Yes/No  when data is required. I just want to know should it be defaulted to yes or no?

Also clicking "Add loan guarantor" will open a new section within the Add loan guarantor space.  Please see below wires

**Comment by MitchellTCG** [comment]
**Please review Loan guarantor - 1012**
![1012 Guarantor – Collapsed.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/3122ef62-7c52-49d5-9280-58df526d0fc5)

When the user clicks "Add loan guarantor" a lookup box will appear.
Ideally I would like the Orange button to be inactive until the user has selected a contact or created a new one. 

![1012 Guarantor.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/29031d3b-b280-4d83-9e8b-1f8bee1e5dc6)

Clicking the orange button will continue to create more guarantors sequentially numbered.

**Comment by MitchellTCG** [comment]
**Please review accordion/step two "Loan Agreement"**
![1011 - Loan Received from Bank – Loan Agreement.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/b1aa9da9-95eb-4a29-acac-4596686df504)

#### TERMS
All of the radio buttons are optional. When you click yes for the following will happen:
![1011 Terms.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/a10e4740-6ed7-4f93-ba8b-2d0fc94fb504)

### CREDIT AMOUNT
![1011 Terms – Credit Amount this Draw.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/da3940be-4505-4531-9304-2b4101ec9e89)

#### Others liable
![1011 Terms – Others liable.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/ddefca16-d265-4d22-9c58-0861c7afcb9d)

#### COLLATERAL
![1011 Terms – Collateral.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/4dca9ef8-7ff3-46dc-86e1-202c019fc7b7)

#### FUTURE INCOM![1011 Future income – Location of account.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/eac72459-6223-49f3-8064-08f2344ef9d1)E
![1011 Future income.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/1fc8c759-1556-49e0-be60-cace7beea24a)

**Comment by AureliaKhorsand** [comment]
@MitchellTCG 

Feedback on #1003:
- Second sentence in top text should maybe read "This loan type requires an associated **receipt.**"
- For toggling YES/NO on if the loan is secured, I'm not sure we should have a default. Is there a reason we don't want to do radio buttons here too? It may just be more consistent with the C1 buttons. If UX-wise it's better to have a default, we should look into which option is most common.
- I'm confused by the extra sentence at the bottom "This loan requires a related transaction". Can we take that out, and just say "Click STEP TWO..."? Also, where can the user see the auto-generated receipt? Shouldn't it be an accordion below the loan agreement? (I know, worlds longest entry form)

Feedback on #1012:
- Please take out "(Required if Amount >$200)" next to Employer/Occupation. We're going to address that help text in a separate ticket. Right now, there is in-line validation if the rule applies.
- Right now there are wires in #1012 already. Can you make sure they're the most updated after these changes?

Feedback on #1011:
- "Date Incurred" will also be auto-generated from the SC Loan and read-only here.
- I'm debating making the fact that the Treasurer auto-populates a separate ticket. Not sure if that changes the wire.
- The order is off, but I assume we can just fix that when putting it in the ticket.
- Again, not seeing a way to see the auto-generated receipt.

**Comment by JonellaCulmer** [comment]
> Only caveats:
Since we have agreed to use radio buttons if yes/no is optional, I have chosen to use a toggle for Yes/No when data is required. I just want to know should it be defaulted to yes or no?

You seem to be using both radio buttons for required and optional across your mockups. Do you mean we should use radio buttons for required and checkbox for optional? I would support this. 

As to the default, in my mind, we have two options. Defaulting to the same option each time, or defaulting to the most commonly used option. The latter meaning that we may have some yes's defaulted and some no's. The latter at the very least sounds like a greater LOE, so for now, let's go with the former and default to the first choice. 

The one exception I see might be for the "others liable" since they are providing information in the form that could affect that section. 

> Also clicking "Add loan guarantor" will open a new section within the Add loan guarantor space. 

The guarantor is added to step 1, correct?

> "This loan requires a related transaction. Click STEP TWO below to enter loan agreement information."

We should avoid words like "click" and "below". Directional words like below are not inclusive. My preference:
"Continue to STEP TWO to add loan agreement information" 

> Accordion changes.

I like the changes, clarifies what about to happen, what needs to be done, and creates a bit more visual interest. One small edit, we should avoid using the Oxford commas. We avoid them on .gov. 

> Authorized representative

Don't like that we plan to include authorized representatives in the list of individuals. That doesn't make sense to me. They are not the same thing.  

> @AureliaKhorsand "Not seeing a way to see the auto-generated receipt..."

Thanks for bringing that up. I commented on the language drafted in [#1178](https://github.com/fecgov/fecfile-web-app/issues/1178#issuecomment-1607989749)

**Comment by MitchellTCG** [comment]
### 1012 C2 Gaurantor
![1012 Guarantor – Collapsed.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/ee90ed22-4100-4ae5-b019-167db77dd079)
![1012 Guarantor.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/02385af6-9779-4018-b91d-c6ea30b25ccc)

**Comment by MitchellTCG** [comment]
### 1011 C1 - Loan Agreement

#### Loan Agreement
![1011 - Loan Received from Bank – Loan Agreement.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/c3702f33-49dc-4615-bd2e-4e57a8d1f419)

#### Term Section
![1011 Terms.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/f33c28fb-e7ef-4632-8e28-5ca68138cd3b)
![1011 Terms – Credit Amount this Draw.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/6d666c01-7969-48fe-9c26-812458588658)


#### Others liable
![1011 Others liable.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/227f335c-f029-4104-a6b0-28fd77ab2842)

#### Collateral
![1011 Collateral.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/5c769866-9256-432d-b19c-f879efed96ce)

#### Future income
![1011 Future income.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/0cef19fc-be22-4530-888c-7257a2f5601c)
![1011 Future income – Location of account.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/d1d3e5e7-cdad-4f53-83ba-f5e5c99eae6d)

#### Authorized representative
![1011 Authorized representative.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/9b373708-bbe6-4431-a13a-501ed0e11786)

**Comment by MitchellTCG** [comment]
### 1005 Loan Received From Bank on Schedule A
![1005 - Loan Received From Bank on Schedule A.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/d45bd094-e3b3-45e3-9ccb-eda18667b9ad)

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
please review

**Comment by AureliaKhorsand** [comment]
#1003 wire looks good. BA approved.

#1012 wire looks good. BA approved.

#1011 feedback:
1. Good news everyone! The optional Y/N are now _required._ We will update the ticket but you can remove "OPTIONAL)" from those fields.
2. Text at the bottom should have commas, not semicolons. 
3. If we include a ToolTip for "Location of Account" in the wire, we need to have the text for what it says. I'm okay with implementing this later.

#1005:
1. Text at the top says to return to previous step to update loan information, but really it's Step One they have to return to.
2. I notice the button says "Save Transactions". What will be our rule for using this language vs "Save" vs "Save both transactions"?

**Comment by MitchellTCG** [comment]
Re: 1003 - Ok
Re: 1012 - Ok
Re: 1011 - 
     1. Duly noted and updated
     2. Although Grammarly and I deeply believe in the use of the semicolon, I have replaced it with commas.
     3. Let make a differ ticket for that. 
     
Re: 1005 
     1. Fixed
     2. it will be Save and Save transactions. (I did not know we would have transactions with more than two accordion sections)

**Comment by AureliaKhorsand** [comment]
Closing as complete since we have finished the initial loan implementation.
