### ISSUE TITLE
UX: Design Form 99

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-project-management#74]
### Select a Form 99
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUxOQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c64d5cbb133d63ce916b2a27b9f0ad985c31f6f3/1103%20Selection.png)

### Form 99 Report
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1BvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--22bba856ee5b15d1ec080b20c9da2703fd6c1ec7/1400%20-%20Form%2099.png)

### Form 99 with dropdown
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1hvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2b2439ccdea5ddaf8550ba775aebb26ed387bbec/1400%20-%20Form%2099%20-%20%20w%20dropdown.png)

### Would you like to compile a print preview?
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0ROQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c1f4c9219e3eb54c6afdffdd105e0bfbb7d303e9/1103%20-%20Would%20you%20like%20to%20compile.png)

### Compiling
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDNmQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--56c87984353a481241f3d9c8cc70e264fcc80783/1103%20-%20Compiling%20your%20preview.png)

### Compiled
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0xOQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7cf16a9138d96099318fbf8803fab233e6a8b3a7/1103%20-%20PDF%20ompiled.png)

### Confirm information
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXZpQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0a41cfa38da4133913172aae266517d656b43a4e/1339%20Confirm%20info.png)

### Submit Report
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXppQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0b885174572bfa5b555cf3c64fd4995b1b5ae13e/1339%20submit%20report.png)

### Are you sure
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0hpQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0df401daccaabf36675754dcaabddba20aaf0e90/1339%20submit%20report%20%E2%80%93%20Are%20you%20sure.png)

**Comment by MitchellTCG** [comment]
@JonellaCulmer @mary-tcg 
Please review the above wireframes 
Use tickets #1103, #1504, #1339 to review ACs

**Comment by MitchellTCG** [comment]
@AureliaKhorsand @GreggMoreland 
Please review Form 99 workflow

**Comment by GreggMoreland** [comment]
@MitchellTCG Should the user be able to Save it and review it or possibly update it before submitting?

A couple of the wires here have Form 24 on them.  Also, the text in the submission for Form 99 should be validated. An amendment is not available for Form 99 (and the text also implies that the user might want to review and change the report before submitting).
