### ISSUE TITLE
UX: Form 1M Notification of Multi-Candidate Status

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-project-management#78]
#### Delete Committee treasurer from the following wireframes:
- [x] Form 1M Initial Load
- [x] Form 1M Radio button errors
- [x] Form 1M Affiliation collapsed
- [x] Form 1M Affiliation expanded
- [x] Form 1M Qualification - State Party collapsed
- [x] Form 1M Qualification - State Party expanded
- [x] Form 1M Qualification - Other collapsed
- [x] Form 1M Qualification - Other error

#### Create Error message wireframes for 
- [x] Qualification
- DATE OF 51st CONTRIBUTION
- DATE OF ORIGINAL REGISTRATION 
- DATE COMMITTEE MET REQUIREMENTS
- [x] Affliction
- AFFILIATED Committee Name
- AFFILIATED Committee ID
- AFFILIATED DATE 

#### (ONLY State party committees may leave this blank.) from the following:
- [x] Form 1M Qualification - State Party collapsed
- [x] Form 1M Qualification - State Party expanded
 
### Select a Form 1M
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHNNQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0ac92dcacecb5376dbd40316392d677c0eaf2a71/1292%20Select.png)

### Select a Form 1M - Selected
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOG9NQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1f18f5c1d707edd8e0924871fc33643097a609f9/1292%20Selected.png)

### Form 1M Initial Load
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVlOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--faf4a4b579339e447988c3749c54e3feff3efa2b/1292%20Initial%20Load.png)

### Form 1M Radio button errors
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWdOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--632c2da583d2023a48e859beb8e118f6d15342c4/1292%20Radio%20errors.png)

### Form 1M Affiliation collapsed
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXNOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7387b5f05a5dc26329f58e520d7a1b4dacc715ac/1292%20-%20Affiliation%20%E2%80%93%20collapsed.png)

### Form 1M Affiliation expanded
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXdOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--65b64475cde35cc1cb8f29829ae6efb77555560d/1292%20-%20Affiliation%20Expanded.png)

### Form 1M Affiliation Errors
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTBOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4a2b02a97f8cf9b050df83efbd65bd6e75b57c72/1292%20-%20Affiliation%20Expanded%20%E2%80%93%20error.png)

### Form 1M Qualification - State Party collapsed
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeThOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--efca1354d44f8f9ce74a926fe59d3d83cfc96abf/1292%20-%20Qualification%20State%20Party%20collapsed.png)

### Form 1M Qualification - State Party expanded
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelVOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--34d7929fc34bd31af77fcbe7a55a32787be55065/1292%20-%20Qualification%20State%20Party%20Expanded.png)

### Form 1M Qualification - Other collapsed
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemNOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e86564e124c1a51711237c5069f0949af413668d/1292%20-%20Qualification%20Other%20collapsed.png)

### Form 1M Qualification - Other expanded
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemdOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--db5e4a0138e7b7795378bbfc6546592556b24b1c/1292%20-%20Qualification%20State%20Party%20Expanded.png)

### Form 1M Qualification - Other error
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemtOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3e2ace3580b9b8ed3a0e4586416a186ae34823be/1292%20-%20Qualification%20Other%20collapsed%20%E2%80%93%20Errors.png)

### Would you like to compile a print preview?
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmZwQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--77d661ba3fb54dba7f4eacb942cd42fab70aa73e/1503%20-%20Would%20you%20like%20to%20compile.png)

### Compiling
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmpwQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bfe42793b17718e7875c2af127cd2398cc6bb5c7/1503%20-%20Compiling%20your%20preview.png)

### Compiled
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNm5wQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ce218efa72434d48444a8b84b421b73ce751ec97/1503%20-%20PDF%20ompiled.png)

## III. Allow user to add report memo text to the Form 1M report - #1502
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnJwQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9be91c645918ebda229dd24f0b6b1623ddb4d191/1502%20-%20report%20level%20memo.png)

### Confirm information
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnZwQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b69a7a9facf46e0cbcf4edb164dae9b5230f1992/1337%20Confirm%20info.png)

### Submit Report
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnpwQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2501d67bc6235f72ab444cfbbc518a27982d3400/1337%20submit%20report.png)

### Are you sure
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjNwQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--568fded79c28354d469fddc81193002c66f0fb07/1337%20submit%20report%20%E2%80%93%20Are%20you%20sure.png)

**Comment by MitchellTCG** [comment]
@AureliaKhorsand @GreggMoreland @mary-tcg @JonellaCulmer 
Would all parties please review? Ping me on Monday if you would like a walk-through. There are A LOT of wires for this.

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg @JonellaCulmer @GreggMoreland  Just a few comments. 

1. We'll need more red validation errors - all three dates are required if the committee chooses qualification, and all three fields are required if the user choose affiliation. Not sure if we want wires to show every single possible red in-line validation or not, but worth calling out.
2. "Form 1M Qualification - State Party expanded" wire still includes the text "(ONLY state party committees may leave this blank)", which should be removed.
3. It looks like we have several screens that have buttons at the bottom right that are either "Sign & Submit report" or "Sign & continue" or "Submit". What is consistent with how we do the Form 3X? Even if that's how it is on the Form 3X, that's a but confusing. It's almost better if they are all "Continue" except for the last one , which is submit. Thoughts?
4. If the user clicks "Save" on the 1M entry form, what happens? Does it just save and keep them on that page? What would indicate a successful save to the user?

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
Re: #3
I pulled the text directly from the app on Stage:
- The button on the "View print preview" page says "Sign & submit report"
- The button on the "Add a report level memo" page says "Save & continue"
- The button on the "Submit report" page says "Submit"

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
Re: #4
When you click "Save" the page will resolve on the "Manage reports" page

**Comment by MitchellTCG** [comment]
Re: #1 - Update Attached
Re: #2 -  Text removed
Re: #5 - per our conversation, we removed the candidate information in the main portion of the Form

**Comment by MitchellTCG** [comment]
@GreggMoreland 
I am adding these to the correct tickets
