### ISSUE TITLE
Increase cloud.gov org memory for FECFile organization to 30 GB

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-project-management#81]
### Business Reason ### 

In order to be able to scale up our applications, we will need more org memory. We should add 15 GB of memory for load testing and scalability.

Org memory tracking sheet: https://docs.google.com/spreadsheets/d/1EsY3zOFv2mv9-f-sf64xbPI8dUGwEawQN2l68aHtO5w/edit#gid=0

Also can double-check with https://github.com/krujos/usagereport-plugin
```
cf install-plugin -r CF-Community "Usage Report"
cf usage-report 
```

Currently, the org memory quota is 15GB. (See screenshot below)

### Acceptance Criteria ### 

Confirm organization memory quota has been increased by viewing info on the cloud.gov dashboard

![image](https://github.com/fecgov/fecfile-project-management/assets/31420082/5a28774f-6f3f-408a-a9e9-2b0b3da63acc)

**Comment by lbeaufort** [comment]
On hold due to budget constraints

**Comment by AureliaKhorsand** [comment]
@lbeaufort should we remove the label for Test Release 1, or is this still need for TR1 but on hold?

**Comment by lbeaufort** [comment]
@AureliaKhorsand this is needed for test release 1, but on hold. cc: @PaulClark2

**Comment by lbeaufort** [comment]
Verified we have 30GB

![Image](https://github.com/fecgov/fecfile-project-management/assets/31420082/76a1768f-29f7-4c61-afb0-d2689170449c)

**Comment by MitchellTCG** [comment]
Approved by client and moved back to Sprint 40
