### ISSUE TITLE
Protoypes for usability Feb 5

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-project-management#82]
#### User Journey 1: 
A user wants to begin working on FECFILE Online (User must have Login.gov account)
- Welcome to FECFILE.gov. Please review our landing page, then log into FECFile. If you do not have a login.gov account, sign up for one.
**File:** Usability 24-1  Login - J1
**Video:** [Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBellhQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--41b2626ee9dd64ad0efed36cc626c7722434ea4c/Usability%2024-1%20%20Login%20-%20J1%20-%20Sign%20Up.mp4)
**Proto:** https://xd.adobe.com/view/0dae0db3-7fc4-4b9a-b38c-fc3e341fa527-58fd/?fullscreen&hints=off
- [x] Jonella
- [ ] Mary

#### User Journey 2: 
A user who HAS BEEN VERIFIED by Login.gov but HAS NOT created a FECFile profile wants to begin working on FECFILE Online.
- Now that uyou have logged into FECFile using Login.gov, please set up your FECFile profile.
**File:** Usability 24-1  Login - J1
**Video:** [Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBem9hQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--074f207c2c0b93ce35ef606e89f884063e33ded5/Usability%2024-1%20%20Login%20-%20J1%20%20Profile.mp4)
**Proto:** https://xd.adobe.com/view/0dae0db3-7fc4-4b9a-b38c-fc3e341fa527-58fd/?fullscreen&hints=off

- [x] Jonella
- [ ] Mary

#### User Journey 3: 
A user who HAS BEEN VERIFIED by Login.gov, HAS created a FECFile profile, and wants to accept the security notification of FECFILE Online. The application will display the notification every time the user accesses FECFile until they consent to the security notification for one year.
- Please review the security notification and consent to the terms to continue your journey
**File:** Usability 24-1  Login - J1
**Video:** [Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWNhQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a700ca6f05b0a90f9f2b44400586105f7b07bf87/Usability%2024-1%20%20Login%20-%20J1.%20Security%20Note.mp4)
**Proto:** https://xd.adobe.com/view/0dae0db3-7fc4-4b9a-b38c-fc3e341fa527-58fd/?fullscreen&hints=off
- [x] Jonella
- [ ] Mary

#### User Journey 4: 
A user can’t sign in because they forgot their Login.gov password.
- Sadly, you forgot your login.gov password. How might you fix that issue?
**File:** Usability 24-1  Login - J8
**Video:** [Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVFaQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c05b1931be4e47560aaad83c62fc89e6b868b0b1/Usability%2024-1%20%20Login%20-%20J8%20-%20Forgot.mp4)
**Proto:** https://xd.adobe.com/view/169ab906-defc-429b-a389-46f5e0d2d6cc-43c9/?fullscreen&hints=off
- [x] Jonella
- [ ] Mary

#### User Journey 5:
A user who HAS BEEN VERIFIED by Login.gov, HAS created a FECFile profile, & HAS been granted permission to work on ONE committee
- Your committee administrator has granted you access **Reagan-Bush '84 (General Election Committee) C00186312**. How might you access this.
**File:** Usability 24-1  Login - J2
**Video:** [Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXdaQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0bbc98941971f3cf57d0e76dbe996a3f71640196/Usability%2024-1%20%20Login%20-%20J5%20-%20One%20Committee.mp4)
**Proto:** https://xd.adobe.com/view/71176ffb-a602-4680-9e74-fa26380b19f0-2444/?fullscreen&hints=off
- [x] Jonella
- [ ] Mary

#### User Journey 6:
A user who HAS BEEN VERIFIED by Login.gov, HAS created a FECFile profile, & HAS been granted permission to work on MULTIPLE committees
- You have already created two committees and Bob, your committee administrator, has granted you access **Reagan-Bush '84 (General Election Committee) C00186312**. How might you access committee **C00186312**.
**File:** Usability 24-1  Login - J4
**Video:** [Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNThaQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--65992ab9e0c791aff1a7d64b88e8dd74ab56276e/Usability%2024-1%20%20Login%20-%20J4%20Multiple.mp4)
**Proto:** https://xd.adobe.com/view/680df01c-206c-4e24-a527-18d8b76b0711-3d5e/?fullscreen&hints=off
- [x] Jonella
- [ ] Mary

#### User Journey 7:
A user who HAS BEEN VERIFIED by Login.gov, HAS created a FECFile profile, & wants to create new committee account on FECFile Online
- Create a new FECFile committee account for **CARTER/MONDALE PRESIDENTIAL COMMITTEE INC (C00344234)**
**File:** Usability 24-1  Login - J3
**Video:** [Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjBhQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--662b9cbd8523891934902f4e5f7c150b5bb84a44/Usability%2024-1%20%20Login%20-%20J4%20Smooth%20Path.mp4)
**Proto:** https://xd.adobe.com/view/831a915b-8c41-4d50-aec4-587c653d475c-d649/?fullscreen&hints=off
- [ ] Jonella
- [ ] Mary

#### User Journey 8:
A user who HAS BEEN VERIFIED by Login.gov, HAS created a FECFile profile, & wants to create new committee account on FECFile Online but Committee C00186312 cannot be found in the FEC global lookup
- Create a new FECFile committee account for **FEC ID: C00186312**
**File:** Usability 24-1  Login - J5
**Video:** [Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2NhQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--90970c987f809a8d91b2d1bbc42d38e8fba11af6/Usability%2024-1%20%20Login%20-%20J5%20Unable%20to%20create.mp4)
**Proto:** https://xd.adobe.com/view/c9f31f04-8c7c-4c02-b34d-4638b95493df-9ca0/?fullscreen&hints=off
- [ ] Jonella
- [ ] Mary

#### User Journey 9:
 A user who HAS BEEN VERIFIED by Login.gov, HAS created a FECFile profile, & wants to create new committee account on FECFile Online but the user's email is not on the Form 1 for C00186312
- Create a new FECFile committee account for **FEC ID: C00186312**
**File:** Usability 24-1  Login - J5
**Video:** [Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2NhQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--90970c987f809a8d91b2d1bbc42d38e8fba11af6/Usability%2024-1%20%20Login%20-%20J5%20Unable%20to%20create.mp4)
**Proto:** https://xd.adobe.com/view/23f57a8c-630f-4d7a-8b64-e19ef307d9da-76a6/?fullscreen&hints=off
- [ ] Jonella
- [ ] Mary

#### User Journey 10:
 A user who HAS BEEN VERIFIED by Login.gov, HAS created a FECFile profile, & wants to create new committee account on FECFile Online for a committee with your email address on the Form 1 but an account already exists
- Create a new FECFile committee account for **FEC ID: C00186312**
**File:** Usability 24-1  Login - J5
**Video:** [Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWdkQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2962a8ae6de230b354c6d3c4fd517ac3a7cf27d7/Usability%2024-1%20%20Login%20-%20J5%20Already%20exist%20form%201.mp4)
**Proto:** https://xd.adobe.com/view/833d5958-2058-41df-8218-afdb3b21d25e-d66e/?fullscreen&hints=off
- [ ] Jonella
- [ ] Mary 

_____________

#### User Journey 1:
As the committee administrator, you need to create a Form 99: Miscellaneous Report to the FEC. Create this form and save it to complete later.
**File:** 1103 - Allow user to create and edit a Form 99
**Video:** [Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWtoQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cfca4127d27ffd320d4db0363bafbda28a14c59e/1103%20-%20Allow%20user%20to%20create%20and%20edit%20a%20Form%2099%20Save.mp4)
**Proto:** https://xd.adobe.com/view/af8f2039-3373-4740-a7e9-2c2b23a49bbe-fadc/?fullscreen&hints=off
- [ ] Jonella
- [ ] Mary

#### User Journey 2:
As the committee administrator, you need to create a Form 99: Miscellaneous Report to the FEC. Create this form and submit it to the FEC.
**File:** 1103 - Allow user to create and edit a Form 99
**Video:** [Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMW9oQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0531efc9d886ffdad4fc22b720e0d8f5d67e9d43/1103%20-%20Allow%20user%20to%20create%20and%20edit%20a%20Form%2099-Rejected.mp4)
**Proto:** https://xd.adobe.com/view/af8f2039-3373-4740-a7e9-2c2b23a49bbe-fadc/?fullscreen&hints=off
- [ ] Jonella
- [ ] Mary

_____________

#### User Journey 1:
As the committee administrator, you need to create a Form 1M. Create this form based on Affiliation and save it to complete later.
**File:** 1292 - Allow user to create and edit Notification of Multi-Candidate Status (Form 1M)
**Video:** 
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3dsQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6ec7d60cd343b10f3d2f7b8bf3a3f1b984aff890/1292%20-%20Allow%20user%20to%20create%20and%20edit%20Notification%20of%20Multi-Candidate%20Status%20%28Form%201M%29%20Affliation.mp4)
**Proto:** https://xd.adobe.com/view/bceb510b-c856-443e-94ea-5964cd185973-e9b8/?fullscreen&hints=off
- [ ] Jonella
- [ ] Mary

#### User Journey 2:
As the committee administrator, you need to create a Form 1M. Create this form based on meeting qualification goal and submit it to the FEC.
**File:** 1292 - Allow user to create and edit Notification of Multi-Candidate Status (Form 1M)
**Video:** [Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHNsQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a8907d0f2d85fd97eae95667469b45ab120559a9/1292%20-%20Allow%20user%20to%20create%20and%20edit%20Notification%20of%20Multi-Candidate%20Status%20%28Form%201M%29%20Qualified.mp4)
**Proto:** https://xd.adobe.com/view/af8f2039-3373-4740-a7e9-2c2b23a49bbe-fadc/?fullscreen&hints=off
- [ ] Jonella
- [ ] Mary

**Comment by mary-tcg** [comment]
1: On the "Add a phone number" page of signing up for login.gov, only the radio button of the 'text message' option is selectable. The whole thing should be a button.

Additionally, there are several typos that I have corrected since taking this screenshot.
<img width="574" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejRmQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1f1de620c89d1af839313400d637a1444fe12d5a/Screenshot%202024-02-01%20134834.png" alt="Screenshot 2024-02-01 134834.png" />

**Comment by JonellaCulmer** [comment]
Login
- Sign in (user journey 1): When submit button not entirely selectable, unless I choose "Remember this browser"
- Forgot password (user journey 4): can be combined with prototype for user journey 1-3, right?
- Forgot password (user journey 4) : Should work if someone has entered email too but no password. 
- User journey 5 should be able to be combined with User journey 1-3 prototype

Form 99
- User journey 2: I don't understand the "edit" part of this journey.

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @JonellaCulmer is this ticket still relevant or can it be closed?
