### ISSUE TITLE
FECFile demo - identify UX/design "polish" opportunities

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-project-management#86]
FECFile demo - identify UX/design "polish" opportunities

@JonellaCulmer's document: 🔒 [https://docs.google.com/document/d/1pEiUAP8UQ6NXx6lKJi5CBHvzNSH1oLPOUhvcN2dN3N8/edit](https://docs.google.com/document/d/1pEiUAP8UQ6NXx6lKJi5CBHvzNSH1oLPOUhvcN2dN3N8/edit) 🔒

### QA Notes ###
 
 null

### DEV Notes ###
 
 null

### Design ###
 
 null

[FECFILE-56](https://fecgov.atlassian.net/browse/FECFILE-56)

**Comment by AureliaKhorsand** [comment]
@JonellaCulmer @lbeaufort can we close this ticket as complete?

**Comment by lbeaufort** [comment]
> @JonellaCulmer @lbeaufort can we close this ticket as complete?

@AureliaKhorsand yes, thanks!
