### ISSUE TITLE
TEST: FECFILE X and Project Management 92

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-project-management#92]
![Image](https://github.com/fecgov/fecfile-project-management/assets/94924171/ef76b68e-15a9-4ff6-9cab-9c4dbc6f70a2)

If I edit the description, is the image still ok in GitHub?

### QA Notes ### 
  
  
  
 null

### DEV Notes ### 
  
  
  
 null

### Design ### 
  
  
  
 null

**Comment by AureliaKhorsand** [comment]
This is a comment originating in GitHub.
